info/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from news.views import *

urlpatterns = patterns('',
    url(r'^$', NewsListView.as_view(), name='news_list'),
    url(r'^(?P<pk>\d+)/$', NewsDetailView.as_view(), name='news_detail'),
)

profiles/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from profiles.views import *

urlpatterns = patterns('',
    url(r'^director/$', login_required(DirectorListView.as_view()), name='director_list'),
    url(r'^director/(?P<pk>\d+)/$', login_required(DirectorDetailView.as_view()), name='director_detail'),
    url(r'^faculty/$', login_required(FacultyListView.as_view()), name='faculty_list'),
    url(r'^faculty/(?P<pk>\d+)/$', login_required(FacultyDetailView.as_view()), name='faculty_detail'),
    url(r'^faculty/new/$', login_required(FacultyCreateView.as_view()), name='faculty_create'),
    url(r'^student/$', login_required(StudentListView.as_view()), name='student_list'),
    url(r'^student/(?P<pk>\d+)/$', login_required(StudentDetailView.as_view()), name='student_detail'),
    url(r'^student/(?P<pk>\d+)/edit/$', login_required(StudentUpdateView.as_view()), name='student_update'),
    url(r'^student/new/$', login_required(StudentCreateView.as_view()), name='student_create'),
)

vishwavidyalaya/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib.auth.decorators import login_required

from vishwavidyalaya.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'vishwavidyalaya.views.home', name='home'),
    # url(r'^vishwavidyalaya/', include('vishwavidyalaya.foo.urls')),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^school/', include('school.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/profile/$', ProfileView.as_view(), name='user_profile'),
    #url(r'^mentee/', include('mentors.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^academics/', include('academics.urls')),
    #url(r'^news/', include('news.urls')),

)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from school.models import Course, Section, Subject, School, Department

from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist

SEX_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
)


class Director(models.Model):
    empID = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(User)
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    school = models.ForeignKey(School)

    def __unicode__(self):
        return '%s %s' %(self.user.first_name, self.user.last_name)

    def get_absolute_url(self):
        return reverse('director_detail', kwargs={'pk': self.id})


class Faculty(models.Model):
    empID = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(User)
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    designation = models.CharField(max_length=50)
    qualification = models.CharField(max_length=300, blank=True, null=True)
    experience = models.PositiveIntegerField(default=0, help_text='in years')
    school = models.ForeignKey(School)
    department = models.ForeignKey(Department)
    phone = models.BigIntegerField(null=True, blank=True)
    alternate_phone = models.BigIntegerField(null=True, blank=True)
    description = models.TextField(blank=True, default='')
    address_street = models.CharField(max_length=350, blank=True, null=True)
    address_city = models.CharField(max_length=100, null=True, blank=True)
    address_state = models.CharField(max_length=30, null=True, blank=True)
    address_pincode = models.IntegerField(null=True, blank=True)
    #is_mentor = models.BooleanField(default=False)
    #is_coordinator = models.BooleanField(default=False)
    #is_hod = models.BooleanField(default=False)

    class Meta():
        verbose_name = 'Faculty'
        verbose_name_plural = 'Faculties'

    def __unicode__(self):
        return '%s %s' %(self.user.first_name, self.user.last_name)

    def get_absolute_url(self):
        return reverse('faculty_detail', kwargs={'pk': self.id})

    def is_hod(self):
        if self.department.hod == self:
            return True
        else:
            return False

    def is_coordinator(self):
        school_courses = Course.objects.filter(department = self.department)
        for course in school_courses:
            if course.coordinator == self:
                return True
        return False

GROUP_CHOICES = (
        (1, 1),
        (2, 2),
)

class Student(models.Model):
    enrollment_number = models.CharField(max_length=15, unique=True, null=True, blank=True)
    exam_roll = models.CharField(max_length=20, null=True, blank=True, unique=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200, blank=True, default='')
    birth_date = models.DateField(null=True, blank=True)
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    email = models.EmailField(null=True, blank=True)
    phone = models.BigIntegerField(null=True, blank=True)
    school = models.ForeignKey(School)
    course = models.ForeignKey(Course)
    section = models.ForeignKey(Section, null=True, blank=True)
    group = models.IntegerField(max_length=1, choices=GROUP_CHOICES, null=True, blank=True)
    subjects = models.ManyToManyField(Subject, null=True, blank=True)

    class Meta:
        permissions = (
                ('view_student', 'Can View Student Profile'),
                )

    def __unicode__(self):
        if self.last_name:
            return '%s %s' %(self.first_name, self.last_name)
        else:
            return self.first_name

    def get_absolute_url(self):
        return reverse('student_detail', kwargs={'pk': self.id})

    def get_full_name(self):
        return self.first_name+' '+self.last_name

school/models.py
from django.db import models
#from profiles.models import Faculty, Student

from django.core.urlresolvers import reverse

SCHOOL_CHOICES = ('Engineering', 'Management', 'Law', 'Applied Sciences', 'Medical')

class School(models.Model):
    name = models.CharField(max_length=300)
    university = models.CharField(max_length=300)
    school_type = models.CharField(max_length=70, choices=zip(SCHOOL_CHOICES, SCHOOL_CHOICES))

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('school_detail', kwargs={'pk': self.id})


class Course(models.Model):
    name = models.CharField(max_length=90)
    duration = models.IntegerField(help_text='in years')
    code = models.CharField(max_length=10)
    department = models.ForeignKey('Department')
    school = models.ForeignKey(School)
    coordinator = models.ForeignKey('profiles.Faculty', null=True, blank=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('course_detail', kwargs={'pk': self.id})

class Department(models.Model):
    name = models.CharField(max_length=50)
    hod = models.ForeignKey('profiles.Faculty', related_name='hod', null=True, blank=True)
    school = models.ForeignKey(School)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('dept_detail', kwargs={'pk': self.id})


class Subject(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=10)
    school = models.ForeignKey(School)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('subject_detail', kwargs={'pk': self.id})

class Section(models.Model):
    name = models.CharField(max_length=100)
    courses = models.ManyToManyField(Course)
    batch = models.IntegerField(help_text='passing year')
    school = models.ForeignKey(School)

    def __unicode__(self):
        return '%s %d' %(self.name, self.batch)

    def get_absolute_url(self):
        return reverse('section_detail', kwargs={'pk': self.id})

SEM_CHOICES = ('I', 'II')
YEARS = ('2012-2013', '2013-2014', '2014-2015')

class Session(models.Model):
    year = models.CharField(max_length=15, choices=zip(YEARS, YEARS))
    semester = models.CharField(max_length=15, choices=zip(SEM_CHOICES, SEM_CHOICES))

    def __unicode__(self):
        return '%s %s' %(self.year, self.semester)

def get_session():
    session_count = Session.objects.all().count()
    return Session.objects.get(id=session_count)

profiles/views.py
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response

from django.views.generic import ListView, CreateView, DetailView, UpdateView

from django.contrib.auth.models import User
from profiles.models import Faculty, Student, Director

class DirectorListView(ListView):
    context_object_name = 'directors'
    template_name = 'director_list.html'
    model = Director

class DirectorDetailView(DetailView):
    context_object_name = 'director'
    template_name = 'director_detail.html'
    model = Director

class FacultyListView(ListView):
    context_object_name = 'faculties'
    template_name = 'faculty_list.html'
    model = Faculty

class FacultyDetailView(DetailView):
    context_object_name = 'faculty'
    template_name = 'faculty_detail.html'
    model = Faculty

class FacultyCreateView(CreateView):
    model = Faculty
    template_name = 'faculty_create.html'

class StudentListView(ListView):
    context_object_name = 'students'
    template_name = 'student_list.html'
    model = Student

class StudentDetailView(DetailView):
    context_object_name = 'student'
    template_name = 'student_detail.html'
    model = Student

class StudentCreateView(CreateView):
    model = Student
    template_name = 'student_create.html'

class StudentUpdateView(UpdateView):
    model = Student
    template_name = 'student_update.html'

templates/base.html
{% load url from future %}
{% load tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block head_title %}VishwaVidyalaya{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="This is college management solution from codesters">
    <meta name="author" content="Karambir Singh Nain">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
      }
      #page-title {
          padding: 20px 0 10px;
          background-color: #9d261d;
          color: #ffffff !important;
          margin-bottom: 20px;
      }
      #page-title small {
        color: #ffffff;
      }
    </style>
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

        {% block extra_head %}{% endblock %}
  </head>

<body>
{% block body %}
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
    <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="brand" href="/">VishwaVidyalaya</a>
        <div class="nav-collapse collapse">
        <ul class="nav pull-right">
            <li class="{% active request "^/$" %}"><a href="/"><i class="icon-home"></i> Home</a></li>
        {% if user.is_authenticated %}
        <li class="{% active request "^/academics/" %}"><a href="{% url 'performance_home' %}"><i class="icon-book"></i> Academics</a></li>
            <li class="{% active request "^/mentor-system/" %}"><a href="#about"><i class="icon-map-marker"></i> Mentor System</a></li>
            <li class="{% active request "^/school/" %} dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-th"></i> School <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'dept_list' %}"><i class="icon-briefcase"></i> Departments</a></li>
                    <li><a href="{% url 'course_list' %}"><i class="icon-tag"></i> Courses</a></li>
                    <li><a href="{% url 'section_list' %}"><i class="icon-pencil"></i> Sections</a></li>
                {% if is_hod or is_director %}
                    <li class="divider"></li>
                    <li class="nav-header"><i class="icon-plus"></i> Add New</li>
                    {% if is_director %}
                    <li><a href="{% url 'dept_create' %}"><i class="icon-briefcase"></i> Department</a></li>
                    {% endif %}
                    <li><a href="{% url 'course_create' %}"><i class="icon-tag"></i> Course</a></li>
                    <li><a href="{% url 'section_create' %}"><i class="icon-book"></i> Section</a></li>
                    <li><a href="{% url 'subject_create' %}"><i class="icon-book"></i> Subject</a></li>
                {% endif %}
                </ul>
            </li>
            <li class="{% active request "^/profiles/" %} dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i> Profiles <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'director_list' %}">Director</a></li>
                    <li><a href="{% url 'faculty_list' %}">Faculty</a></li>
                    <li><a href="{% url 'student_list' %}">Student</a></li>
                {% if is_director or is_hod or is_coordinator %}
                    <li class="divider"></li>
                    <li class="nav-header"><i class="icon-plus"></i> Add New</li>
                    <li><a href="{% url 'student_create' %}">Student</a></li>
                    {% if is_director %}
                    <li><a href="{% url 'faculty_create' %}">Faculty</a></li>
                    {% endif %}
                {% endif %}
                </ul>
            </li>
            <li class="{% active request '^/accounts/' %} dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-asterisk"></i> {{ user.username }} <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'user_profile' %}"><i class="icon-picture"></i> My Profile</a></li>
                    <li><a href="{% url 'user_profile' %}"><i class="icon-wrench"></i> Settings</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'auth_logout' %}"><i class="icon-off"></i> Logout</a></li>
                </ul>
            </li>
        {% else %}
            <li class="{% active request "^/accounts/register/$" %}"><a href="{% url 'registration_register' %}"><i class="icon-download-alt"></i> Register</a></li>
            <li class="{% active request "^/accounts/login/$" %}"><a href="{% url 'auth_login' %}"><i class="icon-download"></i> Login</a></li>
        {% endif %}
        </ul>
      </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar-inner -->
</div><!--/.navbar -->
<div class="row" id="page-title">
    <div class="container">
        <div class="page-header">
            <h1>{% block page_title %}{% endblock %}  <small>{% block page_subtitle %}{% endblock %}</small></h1>
        </div><!--/.page-header -->
    </div>
</div><!--/.page-title -->
<div class="container content">
    {% block content %}{% endblock %}
</div> <!-- /container -->
{% endblock %}
<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ STATIC_URL }}js/jquery.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block head_title %}Welcome Home{% endblock %}
{% block page_title %}Welcome Home{% endblock %}{% block page_subtitle %}{{ user.get_full_name }}{% endblock %}

{% block content %}
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
<h1>Hello, world!</h1>
<p>Manage all student records at one place. Project from <a href="http://codesters.org/">Codesters</a></p>
<p><a href="#" class="btn btn-danger btn-large">Learn more &raquo;</a></p>
</div>

<!-- Example row of columns -->
<div class="row">
<div class="span4">
  <h2>Mentor System</h2>
  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  <p><a class="btn" href="#">View details &raquo;</a></p>
</div>
<div class="span4">
  <h2>Performance</h2>
  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
  <p><a class="btn" href="#">View details &raquo;</a></p>
</div>
<div class="span4">
  <h2>News and Events</h2>
  <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
  <p><a class="btn" href="#">View details &raquo;</a></p>
</div>
</div>
{% endblock %}
<hr>

templates/profile.html
{% extends "base.html" %}

{% block head_title %}Profile Amity University - CSE Dept{% endblock %}
{% block page_title %}Welcome {{ user.get_full_name }}{% endblock %}
{% block content %}
<p class="lead">You have successfully logged in</p>
{% endblock %}